<footer class="footer">
<div class="footer__inner">
<script>
<div class="clearfix">
<div class="footer__logo-area">
<p class="footer__logo img_replace"><a href="/">ごちそう会</a></p>
<p class="footer_txt">"gochikai.com"は「とっておきのごちそうを食べたい。お酒は、いいものを大切に味わいたい。」という大学生の想いから生まれたWEBサイトです。</p>
</div>
<nav class="footer__nav-area">
<ul class="footer__nav">
<li class="footer__nav__list img_replace footer__nav__list--01"><a href="/concept/">CONCEPT ごち会のコンセプト</a></li>
<li class="footer__nav__list img_replace footer__nav__list--02"><a href="/restaurant/tokyo/">RESTAURANT ごち会コースの楽しめるお店</a></li>
<li class="footer__nav__list img_replace footer__nav__list--03">SPECIAL coming soon</li>
<li class="footer__nav__list img_replace footer__nav__list--04"><a href="/enjoyment/">ENJOYMENT ごちそうを楽しむために</a></li>
<li class="footer__nav__list img_replace footer__nav__list--05"><a href="/about/">ABOUT 私たちについて</a></li>
</ul>
</nav>

<div class="footer__info-area">
<ul class="footer__info">
<li class="footer__info__list"><a href="/contact/form/">お問い合わせ</a></li>
<li class="footer__info__list"><a href="/news/">NEWS一覧</a></li>
<li class="footer__info__list"><a href="/terms/">ご利用規約</a></li>
<li class="footer__info__list"><a href="/privacy/">個人情報保護方針</a></li>
</ul>
<div class="footer__social">
<p class="footer__social_fb-page"><a href="https://www.facebook.com/sousyokukei.kanzi" target="_blank">公式Facebookページ</a></p>
<ul class="footer__social__list clearfix">

<li class="footer__social__item"><p class="footer__social__item__tw social__item"><a href="#" onclick="window.open(this.href, 'TWwindow', 'width=650, height=450, menubar=no, toolbar=no, scrollbars=yes'); return false;"><img src="/assets/common/img/footer_social_tw_l.png" data-src="/assets/common/img/footer_social_tw_s.png" alt=""></a></p></li>

<li class="footer__social__item"><p class="footer__social__item__fb"><a href="http://www.facebook.com/sharer.php?u=http://gochikai.com/" onclick="window.open(this.href, 'FBwindow', 'width=650, height=450, menubar=no, toolbar=no, scrollbars=yes'); return false;"><img src="/assets/common/img/footer_social_fb_l.png" data-src="/assets/common/img/footer_social_fb_s.png" alt=""></a></p></li>
</ul>
</div>
</div>

<!-- /.clearfix --></div>
</script>
<p class="footer__page-top"><a href="#sitetop"><img src="/assets/common/img/footer_pagetop_txt.png" alt="PAGE TOP"></a></p>
<!-- /.footer__inner --></div>
<div class="footer__copyright-area">
<div class="footer__opyright-area__inner">
<p class="footer__copyright--txt">飲酒は20歳を過ぎてから。飲酒運転は法律で禁止されています。<br>
妊娠中や授乳期の飲酒は、胎児・乳児の発育に悪影響を与えるおそれがあります。お酒は適量を。</p>
<p class="footer__copyright">GOCHIKAI © All Right Reserved.</p>
</div>
</div>
</footer>
