<div class="content__mask"></div>

<header class="header header--shadow">
<div class="header__inner header__inner--hidden">
<h1 class="header__logo img_replace"><a href="/">ごちそう会</a></h1>
<p class="header__is-btn"><a class="header__is-btn--burger" href="#"><span></span></a></p>
<div class="header__menu header__menu--static">

<!-- 通常ナビ -->
<nav class="header__nav">
<ul class="header__nav__list clearfix">
<li class="header__nav__item header__nav__item--01 img_replace"><a href="/concept/">ごち会のコンセプト</a></li>
<li class="header__nav__item header__nav__item--02 img_replace"><a href="/restaurant/tokyo/">ごち会コースの楽しめるお店</a></li>
<!-- <li class="header__nav__item header__nav__item--03 img_replace">coming soon</li> -->
<li class="header__nav__item header__nav__item--04 img_replace"><a href="/enjoyment/">ごち会のブログ</a></li>
<li class="header__nav__item header__nav__item--05 img_replace"><a href="/about/">ごち会の団体紹介</a></li>
</ul>
</nav>
<!-- /通常ナビ -->

<!-- ミニヘッダー用ナビ -->
<nav class="header__nav--mini">
<ul class="header__nav__list clearfix">
<li class="header__nav__item header__nav__item--01 img_replace"><a href="/concept/">ごち会のコンセプト</a></li>
<li class="header__nav__item header__nav__item--02 img_replace"><a href="/restaurant/tokyo/">ごち会コースの楽しめるお店</a></li>
<!-- <li class="header__nav__item header__nav__item--03 img_replace">SPECIAL coming soon</li> -->
<li class="header__nav__item header__nav__item--04 img_replace"><a href="/enjoyment/">ごち会のブログ</a></li>
<li class="header__nav__item header__nav__item--05 img_replace"><a href="/about/">ごち会の団体紹介</a></li>
</ul>
</nav>
<!-- /ミニヘッダー用ナビ -->

<p class="header__info"><a href="/contact/form/"><img src="/assets/common/img/hdr_menu_btn_l.png" data-src="/assets/common/img/hdr_menu_btn_s.png" alt="お問い合わせ" class="rollover"></a></p>
<div class="header__social clearfix">
<p class="header__social__fb-page"><a href="https://www.facebook.com/sousyokukei.kanzi" target="_blank">公式Facebookページ</a></p>
<ul class="header__social__list clearfix">

<li class="header__social__item"><p class="header__social__item__tw social__item"><a href="#" onclick="window.open(this.href, 'TWwindow', 'width=650, height=450, menubar=no, toolbar=no, scrollbars=yes'); return false;"><img src="/assets/common/img/hdr_sns_tw_l.png" data-src="/assets/common/img/hdr_sns_tw_s.png" alt="Twitter"></a></p></li>

<li class="header__social__item"><p class="header__social__item__fb"><a href="http://www.facebook.com/sharer.php?u=http://gochikai.com/" onclick="window.open(this.href, 'FBwindow', 'width=650, height=450, menubar=no, toolbar=no, scrollbars=yes'); return false;"><img src="/assets/common/img/hdr_sns_fb_l.png" data-src="/assets/common/img/hdr_sns_fb_s.png" alt="Facebook"></a></p></li>
</ul>
<!-- /.header__social --></div>
<!-- /.header__menu --></div>
<!-- PC -->
<p class="header__info header__info--over-menu"><a href="/contact/form/"><span>お問い合わせ</span></a></p>
<!-- /PC -->
<!-- /.header__inner --></div>

<!-- ミニヘッダー -->
<div class="header__mini header--shadow" id="header__mini">
<div class="header__inner">
<div class="header__logo img_replace"><a href="/">ごち会</a></div>
<p class="header__is-btn"><a class="header__is-btn--burger" href="#"><span></span></a></p>
<!-- /.header__inner --></div>
<!-- /.header__mini --></div>
<!-- /ミニヘッダー -->

</header>
